# Generated by Django 5.2.7 on 2025-10-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0002_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationtype",
            name="name",
            field=models.CharField(
                help_text="Пополнение / Списание", max_length=100, verbose_name="Название типа операции"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                help_text="Пример: Бизнес, Личное, Налог, другое", max_length=100, verbose_name="Название статуса"
            ),
        ),
    ]
