# Generated by Django 5.2.7 on 2025-10-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0003_alter_operationtype_name_alter_status_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cash_flow.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="operation_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cash_flow.operationtype",
                verbose_name="Тип операции",
            ),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cash_flow.status",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cash_flow.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="operation_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cash_flow.operationtype",
                verbose_name="Тип операции",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cash_flow.category",
                verbose_name="Категория",
            ),
        ),
    ]
